global:
  scrape_interval: 5s
rule_files:
  - /etc/prometheus/rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.1.114:9100
scrape_configs:
  - job_name: local_host
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9090
  - job_name: local_host_python
    static_configs:
      - targets:
          - host.docker.internal:8000
  - job_name: My_Linux_host
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.1.114:9100